cache: apt
sudo: false
language: python
python:
- '3.5'
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
before_install:
- openssl aes-256-cbc -K $encrypted_cd97de21217c_key -iv $encrypted_cd97de21217c_iv
  -in nsmaps/local_settings.py.enc -out nsmaps/local_settings.py -d
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run test.py
notifications:
  email: false
after_success:
  coveralls
