cache: apt
sudo: false
language: python
python:
  - "2.7"
  - "3.5"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib
  - pip install -r requirements_travis.txt
script: python test.py
notifications:
  email: false
